project:
  type: book

prefer-html: true

book:
  title: "Spatial Data Science"
<<<<<<< HEAD
  subtitle: "With Applications in R and Python"
  author: "Edzer Pebesma, Roger Bivand"
  site-url: https://r-spatial.org/python/
=======
  subtitle: "With Applications in R"
  author:
    - name: Edzer Pebesma
      orcid: 0000-0001-8049-7069
      email: edzer.pebesma@uni-muenster.de
      url: https://www.uni-muenster.de/Geoinformatics/institute/staff/index.php/119/Edzer_Pebesma
      affiliations:
      - name: Universität Münster
        city: Münster
        country: Germany
    - name: Roger Bivand
      orcid: 0000-0003-2392-6140
      email: Roger.Bivand@nhh.no
      url: https://www.nhh.no/en/employees/faculty/roger-bivand/
      affiliations:
      - name: Norwegian School of Economics
        city: Bergen
        country: Norway
>>>>>>> main
  date: today
  repo-url: https://github.com/edzer/sdsr/
  repo-branch: python
  repo-actions: [edit]
  google-analytics:
    tracking-id: "G-04YTZNEH1K"
    storage: none
    anonymize-ip: true
  chapters:
    - index.qmd
    - part: part-1.qmd
      chapters:
        - 01-hello.qmd
        - 02-Spaces.qmd
        - 03-Geometries.qmd
        - 04-Spherical.qmd
        - 05-Attributes.qmd
        - 06-Cubes.qmd
    - part: part-2.qmd
      chapters:
        - 07-Introsf.qmd
        - 08-Plotting.qmd
        - 09-Large.qmd
    - part: part-3.qmd
      chapters:
        - 10-Models.qmd
        - 11-PointPattern.qmd
        - 12-Interpolation.qmd
        - 13-Geostatistics.qmd
        - 14-Areal.qmd
        - 15-Measures.qmd
        - 16-SpatialRegression.qmd
        - 17-Econometrics.qmd
  appendices:
    - sp-raster.qmd
    - rbasics.qmd
    - ERRATA.qmd
    - references.qmd

bibliography: 
  - packages.bib
  - book.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
    R.options:
      knitr.graphics.auto_pdf: true
      dplyr.print_min: 6
      dplyr.print_max: 6
      stars.crs: 17
      digits: 3

format:
  html:
    number-depth: 2
    theme: cosmo
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68
